WebUI/Controllers/DocumentController.cs
using Data.DataModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class DocumentController : BaseController
    {
        // GET: Document
        public ActionResult Index()
        {
            List<TsDocumentEntity> docsForDownload = new List<TsDocumentEntity>();
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/SavedDocBox"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*");

            string userId = User.Identity.GetUserId();
            var dbUserDocs = this.db.TsDocumentEntries.Where(d => d.UserId == userId);

            var admin = db.Users.Where(u => u.Email == "admin@admin.com").FirstOrDefault();
            if (admin != null)
            {
                var defDoc = this.db.TsDocumentEntries.Where(d => d.UserId == admin.Id).FirstOrDefault();
                if (defDoc != null)
                {
                    docsForDownload.Add(defDoc);
                }
            }
            
            if (dbUserDocs != null)
            {
                foreach(var userDoc in dbUserDocs)
                {
                    if (fileNames.Where(i => i.FullName.Contains(userDoc.SavedName)).FirstOrDefault() != null)
                    {
                        docsForDownload.Add(userDoc);
                    }
                }
            }

            var newModel = new TsDocumentViewerModel();

            var docViews = docsForDownload.Select(e=> new TsDocumentListModel()
            {
                TsDocumentEntityId  = e.TsDocumentEntityId,
                DocumentName  = e.DocumentName,
                UserId = e.UserId,
                DocGuid = e.DocGuid,
                SavedName = e.SavedName,
                SystemDefault = e.SystemDefault
            }).ToList();

            newModel.UploadedDocuments = docViews;
            return View(newModel);
            
        }

        public FileResult Download(string SavedName)
        {
            return File("~/SavedDocBox/" + SavedName, System.Net.Mime.MediaTypeNames.Application.Octet);
        }

        [HttpPost]
        public ActionResult Upload(TsDocumentViewerModel model)
        {

            HttpPostedFileBase file = model.DocumentUpload;

            Guid newDocGuid = Guid.NewGuid();

            var userDoc = model.UploadedDocuments.Where(d => !d.SystemDefault).FirstOrDefault();
            if (userDoc!=null)
            {
                newDocGuid = userDoc.DocGuid;
            }

            try
            {
                if (file.ContentLength > 0)
                {

                    string userId = User.Identity.GetUserId();
                    if (!string.IsNullOrEmpty(userId))
                    {
                        TsDocumentEntity newDoc = new TsDocumentEntity();
                        newDoc.UserId = userId;
                        var fileName = Path.GetFileName(file.FileName);
                        newDoc.DocumentName = fileName;
                        //Guid newDocGuid = Guid.NewGuid();
                        newDoc.DocGuid = newDocGuid;
                        newDoc.SavedName = string.Format("TS_{0}.docx", newDocGuid.ToString());
                        var path = Path.Combine(Server.MapPath("~/SavedDocBox"), newDoc.SavedName);
                        file.SaveAs(path);

                        var dbDoc = db.TsDocumentEntries.SingleOrDefault(d => d.UserId == userId);
                        if (dbDoc==null)
                        {
                            dbDoc = new TsDocumentEntity();
                            dbDoc.UserId = userId;
                            dbDoc.SystemDefault = false;
                            dbDoc.DocumentName = newDoc.DocumentName;
                            dbDoc.DocGuid = newDoc.DocGuid;
                            dbDoc.SavedName = newDoc.SavedName;
                            db.TsDocumentEntries.Add(dbDoc);
                        }
                        else
                        {
                            dbDoc.DocumentName = newDoc.DocumentName;
                            dbDoc.DocGuid = newDoc.DocGuid;
                            dbDoc.SavedName = newDoc.SavedName;
                        }
                        db.SaveChanges();
                    }
                }
                ViewBag.Message = "Upload successful";
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Message = "Upload failed";
                return RedirectToAction("Uploads");
            }
        }


    }
}

WebUI/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Data.DataModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using WebUI.Models;

namespace WebUI.Controllers
{
    [System.Web.Mvc.Authorize]
    public class TemplateController : BaseController
    {
        // GET: Template
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var templates =
                this.db.TsWeekTemplates.OrderBy(i => i.TsWeekTemplateId)
                    .Where(e => e.ApplicationUserId == userId)
                    .Select(e => new TsTemplateViewModel()
                    {
                        TsWeekTemplateId = e.TsWeekTemplateId,
                        //ApplicationUserId = userId,
                        TemplateName = e.TemplateName,
                        HoursInDay = e.HoursInDay,
                        //FirstDayOfWeek = e.FirstDayOfWeek,
                        FillDay1 = e.FillDay1,
                        FillDay2 = e.FillDay2,
                        FillDay3 = e.FillDay3,
                        FillDay4 = e.FillDay4,
                        FillDay5 = e.FillDay5,
                        FillDay6 = e.FillDay6,
                        FillDay7 = e.FillDay6,
                        IsDefault = e.IsDefault
                    }).ToList();
            return View(templates);
        }

        
        public ActionResult Create()
        {
            var template = new TsTemplateViewModel();
            //var list = new List<ListItem>();
            //list.Add(new ListItem { Value = DayOfWeek.Sunday.ToString(), Text = Enum.GetName(typeof(DayOfWeek), DayOfWeek.Sunday)});
            //template.ddlFirstDayOfWeek = list;
            return View(template);
        }

        [ValidateAntiForgeryToken]
        [System.Web.Mvc.HttpPost]
        public ActionResult Create(TsTemplateViewModel template)
        {
            if (!ModelState.IsValid)
            {
                return View(template);
            }
            var userId = User.Identity.GetUserId();
            var dbTemplate = new TsWeekTemplate();
            dbTemplate.ApplicationUserId = userId;
            dbTemplate.TemplateName = template.TemplateName;
            dbTemplate.HoursInDay = template.HoursInDay;
            dbTemplate.FillDay1 = template.FillDay1;
            dbTemplate.FillDay2 = template.FillDay2;
            dbTemplate.FillDay3 = template.FillDay3;
            dbTemplate.FillDay4 = template.FillDay4;
            dbTemplate.FillDay5 = template.FillDay5;
            dbTemplate.FillDay6 = template.FillDay6;
            dbTemplate.FillDay7 = template.FillDay7;
            dbTemplate.IsDefault = template.IsDefault;
            dbTemplate.StartTime = template.StartTime;
            dbTemplate.EndTime = template.EndTime;

            db.TsWeekTemplates.Add(dbTemplate);
            db.SaveChanges();

            // un-checking all other isDefault values
            if (dbTemplate.IsDefault)
            {
                var otherTemplates = db.TsWeekTemplates.Where(e => e.ApplicationUserId == userId && e.IsDefault && e.TsWeekTemplateId != dbTemplate.TsWeekTemplateId).ToList();
                if (otherTemplates.Count > 0)
                {
                    foreach (var item in otherTemplates)
                    {
                        item.IsDefault = false;
                    }
                    db.SaveChanges();
                }
            }
            
            

            return View("Index");
        }

        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var template = db.TsWeekTemplates.SingleOrDefault(t => t.TsWeekTemplateId == id && t.ApplicationUserId == userId);
            if (template == null) return HttpNotFound();

            var viewTemplate = new TsTemplateViewModel();
            viewTemplate.TemplateName = template.TemplateName;
            viewTemplate.HoursInDay = template.HoursInDay;
            viewTemplate.TsWeekTemplateId = template.TsWeekTemplateId;
            viewTemplate.FillDay1 = template.FillDay1;
            viewTemplate.FillDay2 = template.FillDay2;
            viewTemplate.FillDay3 = template.FillDay3;
            viewTemplate.FillDay4 = template.FillDay4;
            viewTemplate.FillDay5 = template.FillDay5;
            viewTemplate.FillDay6 = template.FillDay6;
            viewTemplate.FillDay7 = template.FillDay7;
            viewTemplate.IsDefault = template.IsDefault;
            viewTemplate.StartTime = template.StartTime;
            viewTemplate.EndTime = template.EndTime;
            return View(viewTemplate);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult Edit(TsTemplateViewModel template)
        {
            if (!ModelState.IsValid)
                return View(template);
            var userId = User.Identity.GetUserId();
            var dbTemplate = db.TsWeekTemplates.SingleOrDefault(t => t.TsWeekTemplateId == template.TsWeekTemplateId);
            dbTemplate.TemplateName = template.TemplateName;
            dbTemplate.HoursInDay = template.HoursInDay;
            dbTemplate.FillDay1 = template.FillDay1;
            dbTemplate.FillDay2 = template.FillDay2;
            dbTemplate.FillDay3 = template.FillDay3;
            dbTemplate.FillDay4 = template.FillDay4;
            dbTemplate.FillDay5 = template.FillDay5;
            dbTemplate.FillDay6 = template.FillDay6;
            dbTemplate.FillDay7 = template.FillDay7;
            dbTemplate.ApplicationUserId = userId;
            dbTemplate.IsDefault = template.IsDefault;
            dbTemplate.StartTime = template.StartTime;
            dbTemplate.EndTime = template.EndTime;

            db.SaveChanges();

            // un-checking all other isDefault values
            if (dbTemplate.IsDefault)
            {
                var otherTemplates = db.TsWeekTemplates.Where(e => e.ApplicationUserId == userId && e.IsDefault && e.TsWeekTemplateId != dbTemplate.TsWeekTemplateId).ToList();
                if (otherTemplates.Count > 0)
                {
                    foreach (var item in otherTemplates)
                    {
                        item.IsDefault = false;
                    }
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        [System.Web.Mvc.HttpPost]
        public string Delete(int id)
        {
            var dbTemplate = db.TsWeekTemplates.SingleOrDefault(t => t.TsWeekTemplateId == id);
            if (dbTemplate == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            db.TsWeekTemplates.Remove(dbTemplate);
            db.SaveChanges();
            return "success";
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Work Space</title>
    @Styles.Render("~/Content/ej/web/bootstrap-theme/ej.web.all.min.css")
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr")
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ejscripts")
    @RenderSection("scripts2", required: false)
   


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Work Space", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Timesheets", "Index", "Timesheet")</li>
                        
                        <li>@Html.ActionLink("My Templates", "Index", "Template")</li>
                        <li>@Html.ActionLink("Document Management", "Index", "Document")</li>
                    }
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @*@Html.Partial("_Notifications")*@
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Timesheet Management</p>
    </footer>
</div>

    
   
    @RenderSection("scripts", required: false)
    @Html.EJ().ScriptManager()
</body>
</html>

WebUI/Views/Shared/_Notifications.cshtml
@using WebUI.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span> Success! </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}